name: Build and Release

on:
  push:
    tags:
      - 'v*'
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up environment
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
    
    - name: Build
      shell: bash
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          g++ calc_new!!!.cpp -o maimaiDX-calculator.exe
        else
          g++ calc_new!!!.cpp -o maimaiDX-calculator
        fi
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: maimaiDX-calculator-${{ matrix.os }}
        path: |
          maimaiDX-calculator*
          !*.cpp
          !*.hpp

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          artifacts/maimaiDX-calculator-ubuntu-latest/maimaiDX-calculator
          artifacts/maimaiDX-calculator-windows-latest/maimaiDX-calculator.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
